Add tooltip component
js-tasks-ru/htmlcss-20220317_dimau777 pull request #11
Opened 2022-04-05 14:38 UTC by Dimau

2022-04-05 14:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-05 14:59 UTC, GSemikozov requested changes

2022-04-05 14:59 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    width: 22px;
лучше фиксировать саму иконку, а блок может быть разных размеров (вместо иконки например текст)

2022-04-05 23:33 UTC, Dimau commented on 05-lection3/01-tooltip/tooltip.css
> +    width: 22px;
Согласен, поправил

2022-04-05 23:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-05 23:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-06 18:25 UTC, GSemikozov approved these changes

2022-04-06 18:25 UTC, merged