Add modal component
js-tasks-ru/htmlcss-20220317_dimau777 pull request #12
Opened 2022-04-06 12:30 UTC by Dimau

2022-04-06 12:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-06 18:28 UTC, GSemikozov requested changes

2022-04-06 18:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
все что здесь - уносим в .modal, а сам .modal__blur удалим как лишний элемент (он не нужен, фон полупрозрачным можно задать через rgba)

2022-04-06 18:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а здесь уже можно absolute / relative

2022-04-06 18:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 5px 25px 0 0;
тут и ниже - вместо дублирования марджина справа можно у самого окна модалки сделать паддинг справа больше. Но на самом деле и в этом нет смысла)

2022-04-07 09:23 UTC, Dimau commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
Не соглашусь, с одной стороны задать полупрозрачность через rgba вместо opacity можно да, но от выноса "шторки" в отдельный элемент для завешивания основного контента страницы есть другие потенциальные профиты - можно в будущем навешивать отдельно анимацию именно на полупрозрачный фон, и она не затронет само модальное окно. Ну то есть такой подход решает текущую задачу дизайнера и дает задел на будущее, оставим?

2022-04-07 09:28 UTC, Dimau commented on 05-lection3/02-modal/modal.css
> +    margin: 5px 25px 0 0;
У меня крестик выполнен как отдельный HTML элемент и padding у окна модалки указан так, чтобы крестик на свое место встал. Соответственно, надо либо .modal__title и .modal__content помещать в обертку и единый марджин / паддинг у нее выставлять, либо у каждого из этих элементов выставить. 
Есть какой-то альтернативный способ?

2022-04-07 09:30 UTC, Dimau commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
Если все-таки избавимся от отдельного элемента  .modal__blur и растянет общий элемент .modal на весь вьюпорт, то можно да

2022-04-07 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
и тем не менее реализацию лучше скорректировать по комментарию выше - поскольку БЭМ-блок это целостная сущность, и достаточно 1 раз правильно спозиционировать блок, чтобы затем, внутри него выравнивать дочерние элементы. То есть .modal__blur - это просто элемент .modal, который является подложкой .modal__window

2022-04-07 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
значит лучше так и сделать )

2022-04-07 16:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 5px 25px 0 0;
оставить паддинги как в макете, а крестик расположить через абсолют - вот и все)

2022-04-08 13:39 UTC, GSemikozov requested changes

2022-04-08 13:39 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    text-align: right;
а зачем здесь выравниваем по правому краю, чтобы затем всем дочерним элементам явно задавать text-align: left? )

2022-04-11 05:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-11 05:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-11 05:07 UTC, Dimau commented on 05-lection3/02-modal/modal.css
> +    text-align: right;
И правда, это уже не нужно - осталось от времен, когда крестик выравнивал. Удалил все лишние выравнивания текста

2022-04-12 10:46 UTC, GSemikozov approved these changes

2022-04-12 10:46 UTC, merged