Add layout for the inner page
js-tasks-ru/htmlcss-20220317_dimau777 pull request #13
Opened 2022-04-07 09:11 UTC by Dimau

2022-04-07 09:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-07 09:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-07 16:52 UTC, GSemikozov requested changes

2022-04-07 16:52 UTC, GSemikozov commented on components/page/page.css
> +.page__header {
header у нас уже есть, просто переиспользуем, а main + main-wrapper - надо пожалуй вынести в отдельный блок

2022-04-08 08:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-08 08:43 UTC, Dimau commented on components/page/page.css
> +.page__header {
Отрефакторил main + main-wrapper - вынес в отдельный компонент inner-main-block

2022-04-08 09:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 13:38 UTC, GSemikozov approved these changes

2022-04-08 13:38 UTC, merged