Add input text component
js-tasks-ru/htmlcss-20220317_dimau777 pull request #22
Opened 2022-04-15 05:07 UTC by Dimau

2022-04-15 05:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-15 19:46 UTC, GSemikozov requested changes

2022-04-15 19:46 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <label class="text-input">
а вот в случае с form-group заворачивать компонент в label не надо)

2022-04-15 19:46 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__success-icon {
.text-input__success-icon + .text-input__error-icon - ничем не отличаются, чтобы не дублировать код, можно было бы так: .text-input__success-icon, .text-input__error-icon {}

2022-04-19 09:35 UTC, Dimau commented on 07-lection5/04-input/index.html
> +    <label class="text-input">
А почему это плохое решение? 
Альтернативное решение, как я понимаю, связывать label с input через for и id, но это же хуже, чем завернуть все в label, потому что нужно думать об уникальности id для нескольких полей ввода на странице. Если же завернуть в label, то этого в принципе не нужно делать, вроде лучше?

2022-04-19 10:09 UTC, Dimau commented on 07-lection5/04-input/input.css
> +.text-input__success-icon {
Согласен, поправил

2022-04-19 20:15 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <label class="text-input">
здесь суть в том, что это многоуровневый компонент, который состоит из более простых - лейбл + инпут. У элемента формы может и не быть label, а если завернем его в этот тег - то нарушаем семантику. Кроме того, вся область лейбла кликабельна, а что если в этом блоке будут другие кликабельные элементы? Об этом нужно позаботиться

2022-04-22 08:42 UTC, Dimau commented on 07-lection5/04-input/index.html
> +    <label class="text-input">
Понял, ок, поправил

2022-04-22 09:49 UTC, GSemikozov requested changes

2022-04-22 09:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <input type="text" class="text-input__control" placeholder="Placeholder" id="text-input1">
инпут и картинки надо завернуть в общий враппер, чтобы относительно именно этого враппера позиционировать иконки поверх инпута

2022-04-22 14:07 UTC, Dimau commented on 07-lection5/04-input/index.html
> +        <input type="text" class="text-input__control" placeholder="Placeholder" id="text-input1">
ОК, поправил

2022-04-23 15:34 UTC, GSemikozov approved these changes

2022-04-23 15:34 UTC, merged