Add skeleton component
js-tasks-ru/htmlcss-20220317_dimau777 pull request #8
Opened 2022-03-31 05:13 UTC by Dimau

2022-03-31 05:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 14:53 UTC, GSemikozov requested changes

2022-03-31 14:53 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 16px;
чтобы не задавать эти марджины всем возможным элементам-линиях в хедере - лучше 1 раз задать этот отступ на .skeleton__avatar

2022-04-01 19:54 UTC, GSemikozov approved these changes

2022-04-01 19:54 UTC, merged